user:
    path:     /
    defaults: { _controller: "troiswaBackBundle:User:index" }

user_show:
    path:     /{id}/show
    defaults: { _controller: "troiswaBackBundle:User:show" }

user_new:
    path:     /new
    defaults: { _controller: "troiswaBackBundle:User:new" }

user_create:
    path:     /create
    defaults: { _controller: "troiswaBackBundle:User:create" }
    methods:  POST

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "troiswaBackBundle:User:edit" }

user_update:
    path:     /{id}/update
    defaults: { _controller: "troiswaBackBundle:User:update" }
    methods:  [POST, PUT]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "troiswaBackBundle:User:delete" }
    methods:  [POST, DELETE]

user_login:
    path:     /signin
    defaults: { _controller: "troiswaBackBundle:User:signin" }

user_edit_by_admin:
    path:     /{id}/editbyadmin
    defaults: { _controller: "troiswaBackBundle:User:editUserByAdmin" }

