troiswa_front:
    resource: "@troiswaFrontBundle/Resources/config/routing.yml"
    prefix:   /

troiswa_back:
    resource: "@troiswaBackBundle/Resources/config/routing.yml"
    prefix:   /admin




