<?php

namespace troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends EntityRepository
{
    public function findAllBrand()
    {
        $query = $this->createQueryBuilder("brand");

        return $query->getQuery()->getResult();
    }

    public function findAllProductInBrand()
    {

        $query = $this->getEntityManager()
            ->createQuery
            ("
                SELECT brand,prod
                FROM troiswaBackBundle:Brand brand
                LEFT JOIN brand.products prod
             ");

        return $query->getResult();
    }

    public function countProductInBrand($brandtitle)
    {

        //SELECT COUNT(product.id)
        //FROM Product
        //LEFT JOIN brand brd ON brand.id = product.id_brand
        //WHERE brand.title = "apple"

        $query = $this->getEntityManager($brandtitle)
            ->createQuery
            ("
                            SELECT COUNT(prod.id)
                            FROM troiswaBackBundle:Product prod
                            LEFT JOIN  prod.brand brd
                            WHERE brd.title = :title
                      ")
            ->setParameter('title',$brandtitle);

        //dump($query->getSingleScalarResult());die();

        return $query->getSingleScalarResult();
    }
}
