<?php

namespace troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends EntityRepository
{
    public function findAllBrand()
    {
        $query = $this->createQueryBuilder("brand");

        return $query->getQuery()->getResult();
    }

    public function findAllProductInBrand()
    {

        $query = $this->getEntityManager()
            ->createQuery
            ("
                SELECT brand,prod
                FROM troiswaBackBundle:Brand brand
                LEFT JOIN brand.products prod
             ");

        return $query->getResult();
    }
}
