<?php

namespace troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    //Affiche le nombre de catégorie
    public function countCategory()
    {
        $query = $this->createQueryBuilder('cat')
            ->select('COUNT(cat)');

        return $query->getQuery()->getSingleScalarResult();


    }

    // Afficher les catégories dont la position est supérieur à 2 ou $position
    public function displayCategoryByPostion($position)
    {
        $query = $this->createQueryBuilder("cat")
            ->where("cat.position > :posValue")
            ->setParameter("posValue",$position);

        return $query->getQuery()->getResult();
    }

    // afficher les catégorie don la description commence par "Produits"
    public function findCategoryStartByProduit()
    {
        $query = $this->createQueryBuilder("cat")
            ->where("cat.description LIKE 'Produits%' ");

        return $query->getQuery()->getResult();
    }
}
