<?php

namespace troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    //Affiche le nombre de catégorie
    public function countCategory()
    {
        $query = $this->createQueryBuilder('cat')
            ->select('COUNT(cat)');

        return $query->getQuery()->getSingleScalarResult();


    }

    // Afficher les catégories dont la position est supérieur à 2 ou $position
    public function displayCategoryByPostion($position)
    {
        $query = $this->createQueryBuilder("cat")
            ->where("cat.position > :posValue")
            ->setParameter("posValue",$position);

        return $query->getQuery()->getResult();
    }

    // afficher les catégorie don la description commence par "Produits"
    public function findCategoryStartByProduit()
    {
        $query = $this->createQueryBuilder("cat")
            ->where("cat.description LIKE 'Produits%' ");

        return $query->getQuery()->getResult();
    }

    public function findAllCategory()
    {
        $query = $this->createQueryBuilder("cat");

        return $query->getQuery()->getResult();
    }

    public function findAllCategoryOrderByPosition()
    {

        $query = $this->getEntityManager()
            ->createQuery
            ("
                           SELECT cat
                           FROM troiswaBackBundle:Category cat
                           ORDER BY cat.position ASC
                        ");

        return $query->getResult();

    }

    public function findAllProductInCategory()
    {

        $query = $this->getEntityManager()
            ->createQuery
             // je selectionne toutes les categories et tous les produits lié aux categories
             // dans l'entité category
             // jointure avec la table product la proprieté private $products de l'entitée category.
            ("

                           SELECT cat,prod
                           FROM troiswaBackBundle:Category cat
                           LEFT JOIN cat.products prod
                        ");



        //dump($query->getSQL());
        //die();

        return $query->getResult();
    }
}
