<?php

namespace troiswa\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findAllCommentOfOneProduct($id)
    {

        $query = $this->createQueryBuilder("com")
            // com.product et non com.product_id car on est avec
            // des objet ici
            ->where("com.product = :product")
            ->setParameter("product",$id);


        // Undefined method 'findAllCommentOfOneProduct'.
        // The method name must start with either findBy or findOneBy!
        //  si on retourne le résultat de la requette plutot que la requette elle meme.
        return $query;
    }
}
