<?php

namespace troiswa\BackBundle\Repository;

use Doctrine\ORM\EntityRepository;



/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCouponRepository extends EntityRepository
{
    // récupère tous les coupons lié a un utilisateurs
    public function findAllCouponForOneUser($id)
    {

        $query = $this->getEntityManager()
            ->createQuery
            ("
                           SELECT coup, coupon
                           FROM troiswaBackBundle:UserCoupon coup
                           LEFT JOIN coup.user use
                           LEFT JOIN coup.coupon coupon
                           WHERE use.id = :userid
                        ")
            ->setParameter("userid", $id);


        //dump($query->getResult());
        //die();

        return $query->getResult();
    }

}


